### ISSUE TITLE
checkptr: unsafe pointer arithmetic

### ISSUE THREAD

**Issue by efritz** [minio/simdjson-go#16]
I found a previous issue with this error that was marked as resolved: https://github.com/minio/simdjson-go/issues/13. 

I've recently introduced simdjson-go to parse LSIF input for Sourcegraph in https://github.com/sourcegraph/sourcegraph/pull/11703. Running `go test -race` (in the `enterprise/cmd/precise-code-intel-worker/internal/correlation` directory) on this PR results in a checkptr exception:

```go
$ go test -race
fatal error: checkptr: unsafe pointer arithmetic

goroutine 53 [running]:
runtime.throw(0x13b23cc, 0x23)
	/usr/local/go/src/runtime/panic.go:1116 +0x72 fp=0xc000c95a78 sp=0xc000c95a48 pc=0x10749a2
runtime.checkptrArithmetic(0xc000d80002, 0x0, 0x0, 0x0)
	/usr/local/go/src/runtime/checkptr.go:43 +0xb5 fp=0xc000c95aa8 sp=0xc000c95a78 pc=0x1047115
github.com/minio/simdjson-go.parse_string_simd_validate_only(0xc000d80001, 0x12a7, 0xa003ff, 0xc000c95df8, 0xc000c95b58, 0xc000c95b4f, 0x0)
	/Users/efritz/go/pkg/mod/github.com/minio/simdjson-go@v0.1.4/parse_string_amd64.go:39 +0x6d fp=0xc000c95b08 sp=0xc000c95aa8 pc=0x126ccdd
github.com/minio/simdjson-go.parse_string(0xc000d20000, 0x1, 0x4, 0x0)
	/Users/efritz/go/pkg/mod/github.com/minio/simdjson-go@v0.1.4/stage2_build_tape_amd64.go:90 +0x1a9 fp=0xc000c95de8 sp=0xc000c95b08 pc=0x127c349
github.com/minio/simdjson-go.unified_machine(0xc000d80000, 0x12a8, 0xa00400, 0xc000d20000, 0x0)
	/Users/efritz/go/pkg/mod/github.com/minio/simdjson-go@v0.1.4/stage2_build_tape_amd64.go:249 +0x2775 fp=0xc000c95f68 sp=0xc000c95de8 pc=0x1280185
github.com/minio/simdjson-go.(*internalParsedJson).parseMessageInternal.func2(0xc000d20000, 0xc0000a4200, 0xc00001a130)
	/Users/efritz/go/pkg/mod/github.com/minio/simdjson-go@v0.1.4/parse_json_amd64.go:89 +0x67 fp=0xc000c95fc8 sp=0xc000c95f68 pc=0x12828c7
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc000c95fd0 sp=0xc000c95fc8 pc=0x10a7f31
created by github.com/minio/simdjson-go.(*internalParsedJson).parseMessageInternal
	/Users/efritz/go/pkg/mod/github.com/minio/simdjson-go@v0.1.4/parse_json_amd64.go:88 +0x2c4

goroutine 1 [chan receive]:
testing.(*T).Run(0xc0000ee120, 0x13abca8, 0xd, 0x13b7120, 0x1)
	/usr/local/go/src/testing/testing.go:1043 +0x699
testing.runTests.func1(0xc0000ee120)
	/usr/local/go/src/testing/testing.go:1284 +0xa7
testing.tRunner(0xc0000ee120, 0xc0000c7d50)
	/usr/local/go/src/testing/testing.go:991 +0x1ec
testing.runTests(0xc0000be3e0, 0x15e9360, 0x9, 0x9, 0x0)
	/usr/local/go/src/testing/testing.go:1282 +0x528
testing.(*M).Run(0xc000138000, 0x0)
	/usr/local/go/src/testing/testing.go:1199 +0x300
main.main()
	_testmain.go:60 +0x224

goroutine 25 [chan receive]:
github.com/sourcegraph/sourcegraph/enterprise/cmd/precise-code-intel-worker/internal/correlation.correlateFromReader(0x1408c00, 0xc000151740, 0x13a9e94, 0x4, 0x0, 0x0, 0x0)
	/Users/efritz/dev/sourcegraph/sourcegraph/enterprise/cmd/precise-code-intel-worker/internal/correlation/correlate.go:58 +0x6f9
github.com/sourcegraph/sourcegraph/enterprise/cmd/precise-code-intel-worker/internal/correlation.TestCorrelate(0xc0000ee900)
	/Users/efritz/dev/sourcegraph/sourcegraph/enterprise/cmd/precise-code-intel-worker/internal/correlation/correlate_test.go:19 +0x1a4
testing.tRunner(0xc0000ee900, 0x13b7120)
	/usr/local/go/src/testing/testing.go:991 +0x1ec
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1042 +0x661

goroutine 29 [chan receive]:
github.com/minio/simdjson-go.ParseNDStream.func3(0xc00016a840, 0xc00016a900)
	/Users/efritz/go/pkg/mod/github.com/minio/simdjson-go@v0.1.4/simdjson_amd64.go:128 +0x107
created by github.com/minio/simdjson-go.ParseNDStream
	/Users/efritz/go/pkg/mod/github.com/minio/simdjson-go@v0.1.4/simdjson_amd64.go:123 +0x186

goroutine 30 [chan send]:
github.com/minio/simdjson-go.queueError(...)
	/Users/efritz/go/pkg/mod/github.com/minio/simdjson-go@v0.1.4/simdjson_amd64.go:209
github.com/minio/simdjson-go.ParseNDStream.func4(0xc00016a900, 0xc000151770, 0xc00016a8a0, 0xc0000b0180)
	/Users/efritz/go/pkg/mod/github.com/minio/simdjson-go@v0.1.4/simdjson_amd64.go:199 +0x409
created by github.com/minio/simdjson-go.ParseNDStream
	/Users/efritz/go/pkg/mod/github.com/minio/simdjson-go@v0.1.4/simdjson_amd64.go:142 +0x1c9

goroutine 50 [chan receive]:
github.com/sourcegraph/sourcegraph/enterprise/cmd/precise-code-intel-worker/internal/correlation/lsif.Read.func1(0xc000d00060, 0xc00016a840, 0x140c360, 0xc0000999c0)
	/Users/efritz/dev/sourcegraph/sourcegraph/enterprise/cmd/precise-code-intel-worker/internal/correlation/lsif/reader.go:37 +0x5bb
created by github.com/sourcegraph/sourcegraph/enterprise/cmd/precise-code-intel-worker/internal/correlation/lsif.Read
	/Users/efritz/dev/sourcegraph/sourcegraph/enterprise/cmd/precise-code-intel-worker/internal/correlation/lsif/reader.go:34 +0xe9

goroutine 51 [semacquire]:
sync.runtime_Semacquire(0xc00001a138)
	/usr/local/go/src/runtime/sema.go:56 +0x42
sync.(*WaitGroup).Wait(0xc00001a130)
	/usr/local/go/src/sync/waitgroup.go:130 +0xd4
github.com/minio/simdjson-go.(*internalParsedJson).parseMessageInternal(0xc000d20000, 0xc000d80000, 0x12a9, 0xa00400, 0x1, 0x0, 0x0)
	/Users/efritz/go/pkg/mod/github.com/minio/simdjson-go@v0.1.4/parse_json_amd64.go:98 +0x2d2
github.com/minio/simdjson-go.(*internalParsedJson).parseMessageNdjson(...)
	/Users/efritz/go/pkg/mod/github.com/minio/simdjson-go@v0.1.4/parse_json_amd64.go:56
github.com/minio/simdjson-go.ParseNDStream.func4.1(0xc0000b0180, 0xc000151770, 0xc000d80000, 0x12a9, 0xa00400, 0xc000022060)
	/Users/efritz/go/pkg/mod/github.com/minio/simdjson-go@v0.1.4/simdjson_amd64.go:180 +0xf2
created by github.com/minio/simdjson-go.ParseNDStream.func4
	/Users/efritz/go/pkg/mod/github.com/minio/simdjson-go@v0.1.4/simdjson_amd64.go:168 +0x348
exit status 2
FAIL	github.com/sourcegraph/sourcegraph/enterprise/cmd/precise-code-intel-worker/internal/correlation	0.237s
```

Go version: 

```go
$ go version
go version go1.14.3 darwin/amd64
```

I'm fairly certain that I'm not misusing the library. At first I thought it may be a concurrency issue, but after simplifying the reading off of the parsed stream the issue still occurs. The files `enterprise/cmd/precise-code-intel-worker/internal/correlation/lsif/reader.go` and `enterprise/cmd/precise-code-intel-worker/internal/correlation/lsif/unmarshal.go` are the only files with code relevant to this failure. (cc @klauspost - this project was recommended from [this reddit post](https://www.reddit.com/r/golang/comments/hdsrjr/performance_improvements_in_precise_code_intel/)).

Let me know if I can provide additional context.

**Comment by efritz** [comment]
I was not able to run `go test -race` on the master branch of this repo without a timeout. Not sure if this needs to be raised in order to pass.

**Comment by fwessels** [comment]
Thank you for submitting the error, we will investigate.

**Comment by efritz** [comment]
Thanks! Let me know if I can help you reproduce or minimize the example.

**Comment by fwessels** [comment]
It may be related to streaming behaviour and buffer reuse in combination with pointing back into the original JSON stream for string values that can remain unchanged (for instance have no escaped unicode characters).

Can you try the following branch to see if this does not show the same behaviour: https://github.com/minio/simdjson-go/tree/experim-always-copy 
(as you can see it is a pretty minimal change, just making sure that an explicit copy is made for each string (which will have a negative impact on performance and memory use)).

**Comment by efritz** [comment]
Looks like that fixes the issue.

```
$ go get -u github.com/minio/simdjson-go@experim-always-copy
go: github.com/minio/simdjson-go experim-always-copy => v0.1.5-0.20200626222352-3ad39a3a93d5
go: downloading github.com/minio/simdjson-go v0.1.5-0.20200626222352-3ad39a3a93d5
go: finding module for package github.com/mmcloughlin/avo/build
go: finding module for package github.com/mmcloughlin/avo/reg
go: finding module for package github.com/mmcloughlin/avo/buildtags
go: finding module for package github.com/mmcloughlin/avo/operand
go: found github.com/mmcloughlin/avo/build in github.com/mmcloughlin/avo v0.0.0-20200523190732-4439b6b2c061
go: golang.org/x/tools upgrade => v0.0.0-20200626171337-aa94e735be7f
go: github.com/klauspost/compress upgrade => v1.10.10
go: golang.org/x/xerrors upgrade => v0.0.0-20191204190536-9bdfabe68543
go: github.com/klauspost/cpuid upgrade => v1.3.0
go: downloading github.com/klauspost/cpuid v1.3.0

$ go test -race
PASS
ok  	github.com/sourcegraph/sourcegraph/enterprise/cmd/precise-code-intel-worker/internal/correlation	0.236s
```

**Comment by efritz** [comment]
> It may be related to streaming behaviour and buffer reuse in combination with pointing back into the original JSON stream for string values that can remain unchanged (for instance have no escaped unicode characters).

I'm assuming the buffer reuse is internal and not something I'm doing illegal with the API?

**Comment by fwessels** [comment]
Good to see that it fixes the issue.

No, it is not related to the API itself. The only way to really avoid it is to have the full JSON message in memory and release the simdjson object before releasing the buffer containing the JSON message. When the message is being streamed then the current behaviour can cause problems because memory may be reused.

The "fix" above addresses this issue at the expense of less performance/more memory use but for certain scenarios that is probably a price that needs to be paid. 

We need to think a little about how to best embed this into the current implementation, so we'll get back on that.

**Comment by fwessels** [comment]
As per commit 8bb4c3f the default behaviour has been changed to always copy out strings to the String buffer.

**Comment by fwessels** [comment]
@efritz can you test if this still resolves your issue?

**Comment by efritz** [comment]
I can build/test without errors now!

**Comment by fwessels** [comment]
Good to hear, closing the issue.
